// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PotoDocs.API.Models;

#nullable disable

namespace PotoDocs.API.Migrations;

[DbContext(typeof(PotodocsDbContext))]
[Migration("20240928132227_Init")]
partial class Init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("PotoDocsAPI.Models.CMRFile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("OrderId")
                    .HasColumnType("int");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("CMRFiles");
            });

        modelBuilder.Entity("PotoDocsAPI.Models.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CompanyNIP")
                    .HasColumnType("int");

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CompanyOrderNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DaysToPayment")
                    .HasColumnType("int");

                b.Property<int>("DriverId")
                    .HasColumnType("int");

                b.Property<DateOnly>("InvoiceIssueDate")
                    .HasColumnType("date");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LoadingAddress")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LoadingDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PDFUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PaymentMade")
                    .HasColumnType("bit");

                b.Property<float>("Price")
                    .HasColumnType("real");

                b.Property<DateTime>("UnloadingAddress")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UnloadingDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("DriverId");

                b.ToTable("Orders");
            });

        modelBuilder.Entity("PotoDocsAPI.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastMyProperty")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("PotoDocsAPI.Models.CMRFile", b =>
            {
                b.HasOne("PotoDocsAPI.Models.Order", "Order")
                    .WithMany("CMRFiles")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Order");
            });

        modelBuilder.Entity("PotoDocsAPI.Models.Order", b =>
            {
                b.HasOne("PotoDocsAPI.Models.User", "Driver")
                    .WithMany()
                    .HasForeignKey("DriverId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Driver");
            });

        modelBuilder.Entity("PotoDocsAPI.Models.Order", b =>
            {
                b.Navigation("CMRFiles");
            });
#pragma warning restore 612, 618
    }
}
